# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='Phone',
            new_name='phone',
        ),
    ]
