# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 11:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('accounts', '0003_auto_20180611_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('postal_code', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('logo', models.ImageField(upload_to='organization/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='accounts.Address')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_member', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '7543036718'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_address', to='accounts.Address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_phone_number', to='accounts.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_phone_number', to='accounts.PhoneNumber'),
        ),
    ]
